In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# normal array
arr = [1,2,3,4,5]

np_arr = np.array([22,33,44,55])
print(arr)
print(np_arr)

print(type(arr))
print(type(np_arr))


[1, 2, 3, 4, 5]
[22 33 44 55]
<class 'list'>
<class 'numpy.ndarray'>


In [3]:
a = np.array(50)
b = np.array([1,2,3,4,5,6,7,8,9,10])
c = np.array([[1,2,3], [4,5,6]])
d  = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [4]:
arr = np.array([1,2,3,4,5], ndmin=5)
print(arr.ndim)

5


In [5]:
print(c[1, 0 ])

4


In [6]:
print(d[1, 0, 2 ])

9


In [7]:
print(b[2:])

[ 3  4  5  6  7  8  9 10]


In [8]:
print(b)

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
print(b[:5])

[1 2 3 4 5]


In [10]:
print(b[2:7])

[3 4 5 6 7]


In [11]:
print(b[:-1])

[1 2 3 4 5 6 7 8 9]


In [12]:
print(b[-1:])

[10]


In [13]:
print(b[-3:-1])

[8 9]


In [14]:
print(b[-7:-3])

[4 5 6 7]


In [15]:
print(b[:7])

[1 2 3 4 5 6 7]


In [16]:
print(b[-7:7])

[4 5 6 7]


In [17]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
b[1:8:2]

array([2, 4, 6, 8])

In [19]:
b[::2]

array([1, 3, 5, 7, 9])

In [20]:
b[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [21]:
b = np.array([1,2,3,4,5,6,7,8,9,10])

print(b.dtype)

int32


In [22]:
str = np.array([1,2,3,4,5,6,7,8,9,10], dtype="S")
print(str.dtype)

|S2


In [23]:
str = np.array([1,2,3,4,5,6,7,8,9,10], dtype="f")
print(str.dtype)

float32


In [24]:
str = np.array([1,2,3,4,5,6,7,8,9,10], dtype="i4")
print(str.dtype)

int32


In [25]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

arr2 = arr.copy() # its not change the original array

arr[0] = 33

print(arr)
print(arr2)


[33  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [26]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

arr2 = arr.view() # change oiginal array

arr[0] = 33

print(arr)
print(arr2)


[33  2  3  4  5  6  7  8  9 10]
[33  2  3  4  5  6  7  8  9 10]


In [27]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

a = arr.copy()
b = arr.view()

print(a.base)
print(b.base)



None
[ 1  2  3  4  5  6  7  8  9 10]


In [28]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [29]:
x = np.array([1,2,3,4,5], ndmin=5)

print(x.shape)


(1, 1, 1, 1, 5)


In [30]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])


arr = arr.reshape(3, 4)

print(arr.shape)


(3, 4)


In [31]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(arr.reshape(2, 3, 2))


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [32]:
arr.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [33]:
arr = np.array([[1, 2, 3], [4, 5, 6]])


for i in arr: 
    for j in i:
        print(j)



1
2
3
4
5
6


In [34]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for i in arr:
    for j in i:
        for z in j:
            print(z)


1
2
3
4
5
6
7
8
9
10
11
12


In [35]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for i in np.nditer(arr):
    print(i)


1
2
3
4
5
6
7
8
9
10
11
12


In [36]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for i in np.nditer(arr[:, ::2]):
    print(i)

1
2
3
7
8
9


In [37]:
for index, i in np.ndenumerate(arr):
    print(index, i)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


In [38]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr3 = np.concatenate((arr1 , arr2))

print(arr3)


[1 2 3 4 5 6]


In [39]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [40]:
arr1 = np.array([1, 2])
arr2 = np.array([5, 6])


# arr3 = np.stack((arr1, arr2), axis=1)

# hstack contate row
# arr3 = np.hstack((arr1, arr2))

# vstack concate column
arr3 = np.vstack((arr1, arr2))

print(arr3)


[[1 2]
 [5 6]]


In [41]:
arr = np.array([1,2,3,4,5,6,7,8,9,10, 11,12])
new_arr = np.array_split(arr, 4)
print(new_arr)


[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]


In [42]:

print(new_arr[0])
print(new_arr[1])

[1 2 3]
[4 5 6]


In [43]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

new_arr = np.array_split(arr, 3)

print(new_arr[0])
print(new_arr[1])
print(new_arr[2])


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


In [44]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

new_arr = np.array_split(arr, 3, axis=1)

print(new_arr[0])


[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]


In [45]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# x = np.where(arr == 4)
x = np.where(arr%2 == 0)

print(x)



(array([ 1,  3,  5,  7,  9, 11], dtype=int64),)


In [46]:
arr = np.array([6, 7, 8, 9])
# x = np.searchsorted(arr, 9)

x = np.searchsorted(arr, 7, side="right")

print(x)

2


In [47]:
# arr = np.array(['banana', 'cherry', 'apple'])

# arr = np.array([True, False, True])

# arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))


[6 7 8 9]


In [48]:

x = np.random.randint(100)

print(x)


46


In [49]:
x = np.random.rand()

print(x)

0.11206991829289992


In [50]:
x = np.random.randint(100, size=(3, 5))

print(x)

[[33 11  0 60 12]
 [63 11 40 68  0]
 [73 13 89 68 48]]


In [51]:
x = np.random.rand(3, 5)

print(x)



[[0.56761245 0.84177742 0.59121717 0.90744321 0.20564613]
 [0.41143469 0.08698559 0.82399389 0.98933488 0.6543368 ]
 [0.22912858 0.20964101 0.56705872 0.48795345 0.66810698]]


In [52]:

x = np.random.choice([3,6,7,1])

print(x)



7


In [106]:
ones = np.ones((2,3))

ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [108]:
type(ones)

numpy.ndarray

In [110]:
zeros = np.zeros((2,3))

zeros

array([[0., 0., 0.],
       [0., 0., 0.]])